### ISSUE TITLE
Undefined error when trying to create a QnA Service

### ISSUE THREAD

**Issue by vdatl5** [MicrosoftLearning/mslearn-ai900#8]
When we try to create a QnA service using the settings provided, when I go to the final review and create page, and click create, it turns up with an "undefined" error. This error was occurring both through the VM and when I tried to do the same outside the VM.

**Comment by sherzyang** [comment]
Thanks @vdatl5. I've had one or two occasions where I've had trouble creating a Web App Bot due to a system bug but haven't had that issue creating the QnA Maker before. I just did a test of lab 11 and it seems to be working for me. Can you test it again? If you are still having trouble, I'd suggest (a) see if changing the location makes a difference, and (b) see if the resource group you are using has restrictions on pricing tier. If you're still encountering this issue, let me know.
